### ISSUE TITLE
RuntimeError: cudaErrorInitializationError(3): initialization error

### ISSUE THREAD

**Issue by lihuining** [changwoonchoi/3Doodle#5]
I encountered this error when runing the viewer.py, my torch Version: 1.12.1 and cuda is 11.3, I can use cuda in pytorch but I cannot figure out why this error.

the full error message is:
[exp_dir] ./logs/sanity_check/bezier/mic_0
[polyscope] Backend: openGL3_glfw -- Loaded openGL version: 3.3.0 NVIDIA 465.19.01
Loaded checkpoints from the given path.
Traceback (most recent call last):
  File "/media/allenyljiang/564AFA804AFA5BE5/Codes/3Doodle/viewer.py", line 258, in <module>
    Viewer(args)
  File "/media/allenyljiang/564AFA804AFA5BE5/Codes/3Doodle/viewer.py", line 49, in __init__
    ps.show()
  File "/home/allenyljiang/anaconda3/envs/3Doodle/lib/python3.10/site-packages/polyscope/core.py", line 25, in show
    psb.show()
  File "/media/allenyljiang/564AFA804AFA5BE5/Codes/3Doodle/viewer.py", line 160, in ps_callback
    self.draw()
  File "/home/allenyljiang/anaconda3/envs/3Doodle/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/media/allenyljiang/564AFA804AFA5BE5/Codes/3Doodle/viewer.py", line 249, in draw
    self.render_buffer.update_data_from_device(rendered_image)
  File "/home/allenyljiang/anaconda3/envs/3Doodle/lib/python3.10/site-packages/polyscope/managed_buffer.py", line 81, in update_data_from_device
    mapped_buffer = self.get_mapped_buffer_CUDAOpenGL()
  File "/home/allenyljiang/anaconda3/envs/3Doodle/lib/python3.10/site-packages/polyscope/managed_buffer.py", line 114, in get_mapped_buffer_CUDAOpenGL
    CUDAOpenGLMappedTextureBuffer(
  File "/home/allenyljiang/anaconda3/envs/3Doodle/lib/python3.10/site-packages/polyscope/device_interop.py", line 320, in __init__
    self.resource_handle = device_interop_funcs['register_gl_image_2d'](self.gl_attribute_native_id)
  File "/home/allenyljiang/anaconda3/envs/3Doodle/lib/python3.10/site-packages/polyscope/device_interop.py", line 158, in <lambda>
    check_cudart_err(cudart.cudaGraphicsGLRegisterImage(
  File "/home/allenyljiang/anaconda3/envs/3Doodle/lib/python3.10/site-packages/polyscope/device_interop.py", line 96, in check_cudart_err
    raise RuntimeError(format_cudart_err(err))
RuntimeError: cudaErrorInitializationError(3): initialization error

**Comment by changwoonchoi** [comment]
Hi, can you try as I mentioned in this issue #3 ?

**Comment by lihuining** [comment]
Yes, I haved tried to set the PATH in the activate.sh ,but I still encountered this error
![image](https://github.com/user-attachments/assets/dfe0aaa0-5292-4854-90f7-df025777a33a)

**Comment by lihuining** [comment]
> Hi, can you try as I mentioned in this issue #3 ?

Yes, I haved tried to set the PATH in the activate.sh ,but I still encountered this error
![image](https://github.com/user-attachments/assets/dfe0aaa0-5292-4854-90f7-df025777a33a)

**Comment by changwoonchoi** [comment]
Hi, Dawn wrote a detailed instruction to set an environment. Please refer to it! (Issue https://github.com/changwoonchoi/3Doodle/issues/9)
